language: ruby

rvm:
  - 2.2.3

#bundler_args: --without development

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update && sudo apt-get install --only-upgrade openssl libssl-dev

script: bundle exec rake db:create db:migrate db:test:prepare
script: bundle exec rake spec

#env:
#  - DB=postgres
